---
title: "Lab News"
---

## 2024

### July

- Meltem delivered an invited presentation titled "A Battle of Wits: Comparing the Capabilities of Generative AI and Humans in Scale Development" as a finalist in the IMPS 2024 Graduate Research Competition in Prague, showcasing the collaborative research proposed with Winnie and Jimmy.

- Meltem presented two posters at IMPS 2024, titled "Comparing traditional measurement invariance and alignment approaches to data harmonization" and "Does deleting biased items make selection fairer and more accurate?"


### June

- Meltem, Winnie, and Jimmy's submission for the IMPS 2024 [Graduate Research Competition on the use of generative AI to advance psychometric research](https://www.psychometricsociety.org/imps2024-graduate-research-call-for-proposals) was selected as one of the top three proposals.

## 2023

### November

- Winnie and Mark are co-authors of the paper ["Prenatal testosterone synchrony in first-time parents predicts fathers' postpartum relationship quality"](https://www.sciencedirect.com/science/article/abs/pii/S0018506X23001381) in press in *Hormones and Behavior*. The first author, Sofi Cardenas, who is a graduate researcher at USC, applies Bayesian multilevel modeling in this work.

### October

- Mark is a co-author of the paper ["Parent Aggression Exposure and Negative Expectancies in Couple Conversation: Rejection Sensitivity as a Mediator"](https://link.springer.com/article/10.1007/s10896-023-00635-2) in press in the *Journal of Family Violence*. The first author, Lexy Beale, who is a graduate researcher at USC, applies multilevel analysis in this work.

### September

- Mark co-authored the article titled ["Comparing MIMIC and MIMIC-interaction to Alignment Methods for Investigating Measurement Invariance concerning a Continuous Violator"](https://www.tandfonline.com/doi/abs/10.1080/10705511.2023.2240517) in the journal *Structural Equation Modeling*. The first author, Yuanfang Liu, a former Ph.D. student of Mark's, is currently a post doc at Purdue University.

- Yichi and Mark are co-authors of the paper ["Measurement Invariance of the Neurobehavioral Symptom Inventory in Male and Female Million Veteran Program Enrollees Completing the Comprehensive Traumatic Brain Injury Evaluation"](https://journals.sagepub.com/doi/abs/10.1177/10731911231198214) in press in *Hormones and Behavior*. This paper applies measurement invariance analysis and quantifies the impact of gender on classification accuracy.

- Mark co-authored the article titled ["Sedentary Behavior and Incident Dementia Among Older Adults"](https://jamanetwork.com/journals/jama/article-abstract/2809418) in *JAMA*.

### August

- Mark is promoted to Associate Professor of Psychology at USC with tenure.
- Yichi completed an internship at Pearson on evaluation of reliability indices for automated scoring algorithms.
- Meltem completed an Data and Statistical Sciences internship at Genentech in which she explored the interval level treatment of ordinal patient reported outcome (survey) data in clinical trials.
- Meltem received her MA in Psychology from USC.

### July

- Yichi presented a project titled "Alignment with Bayesian Region of Measurement Equivalence (ABROME) Approach for Multiple Groups Comparisons" in IMPS.
- Winnie presented a project titled "Addressing Publication Bias and Uncertainty for Power Analysis: A Hybrid Classical-Bayesian Approach" in IMPS.
- Jimmy presented "Modeling Latent Interaction Effects: A Two-Stage Path Analysis Approach (2S-PA)" in EAM.

### April 

- Winnie presented a paper titled "Addressing Uncertainty in Power Analysis for Designing Cluster Randomized Trials" at the American Educational Research Association (AERA) 2023 Annual Meeting in Chicago. 
- Yichi presented a paper titled "Investigating Measurement Invariance in NAEP Student Questionnaire Index Items" at the National Council on Measurement in Education (NCME) 2023 Annual Meeting in Chicago.
- Yichi presented a poster titled "An empirical Bayes cluster-mean approach to correct for sampling error in between-cluster effects" at the American Educational Research Association (AERA) 2023 Annual Meeting in Chicago.
- Winnie received the Excellence in Scientific Writing in the Psychology Department at USC. 
- Jimmy presented his project titled "A Systematic Review of Measurement Invariance Research of the CES-D across Gender" at the poster party. 

### February 

- Mark has a co-authored article titled ["The Impacts of the COVID-19 Pandemic on Therapy Utilization Among Racially/Ethnically and Socio-Economically Diverse Autistic Children,"](https://link.springer.com/article/10.1007/s10803-023-05905-y) in press in the *Journal of Autism and Developmental Disorders*. The first author is Cassie Gonzalez who is a graduate researcher at USC, and she applies multilevel modeling in this work.

## 2022
### November 

- Winnie and Yichi passed their qualifying exams and defended their dissertation proposals. Congratulations to Winnie and Yichi!

### September

- Mark is the recipient of the NSF CAREER Scientist Award and starts the funded project in September. Congratulations to Mark!
- Meltem presented a poster titled "Evaluating the Effectiveness and Equity of Court Interventions to Reduce Involvement with the Criminal Justice System" at the Learning & Doing Data for Good (LDDG) Conference at the University of Washington.

### June to August

- Meltem was selected as a Data Science for Social Good (DSSG) Fellow and completed the 3-month full-time DSSG fellowship at Carnegie Mellon which aims to "train aspiring data scientists to work on machine learning, data science, and AI projects with social impact in a fair and equitable manner."

### June 

- Yichi did a summer internship at American Institutes for Research. 

## 2021
### July 

- We welcomed our fourth graduate student Meltem Ozcan to the lab.
- Mark authored article titled "Adjusting for Measurement Noninvariance with Alignment in Growth Modeling" in journal Multivariate Behavioral Research.

## 2020
### August 

- We welcomed our third graduate student Jimmy Zhang to the lab.

### July 

- Winnie and Yichi presented posters at the International Meeting of Psychometric Society (IMPS) online.

## 2019
### August 

- MMM lab established.
- We welcomed our first two graduate students Winnie Tse and Yichi Zhang to the lab.
