---
title: Selected Publications
author: 'MMM'
date: '2020-05-28'
slug: publications
categories: []
tags: []
---

## Peer-Reviewed Articles (Selected)

### In Press

- Lai, M. H. C. (2020 April 20). Composite reliability of multilevel data: It's about observed scores and construct meanings. *Psychological Methods.* Manuscript accepted for publication.

### 2020

- Lai, M. H. C. (2020). Bootstrap confidence interval for multilevel standardized effect size. *Multivariate Behavioral Research.* Advance online publication. https://doi.org/10.1080/00273171.2020.1746902

### 2019

- Lai, M. H. C. (2019). Correcting fixed effect standard errors when a crossed random effect was ignored for balanced and unbalanced data. *Journal of Educational and Behavioral Statistics, 44*, 448-472. https://doi.org/10.3102/1076998619843168
- Lai, M. H. C. (2019). Quantifying the impact of partial measurement invariance in diagnostic research: An application to addiction research. *Addictive Behaviors, 94*, 50-56. https://doi.org/10.1016/j.addbeh.2018.11.029

<hr>

## Conference Presentations

### 2020

<p>
- Lai, M. H. C. (2020, July). *Multilevel bootstrap confidence intervals for standardized effect size* [Paper Session]. Annual Meeting of the Psychometric Society (IMPS), College Park, MD, United States. [Schedule](https://www.psychometricsociety.org/sites/main/files/file-attachments/imps_2020_virtual_schedule_g1.pdf?1594692842)
- Tse, W. W. & Lai, M. H. C. (2020, July 14-17). *Measurement Invariance for Ordered Categorical Variables: The Necessity of Strict Invariance for Valid Group Comparisons* [Poster Session]. Annual Meeting of the Psychometric Society (IMPS), College Park, MD, United States. [Schedule](https://www.psychometricsociety.org/sites/main/files/file-attachments/imps_2020_virtual_schedule_g1.pdf?1594692842)
- Zhang, Y. & Lai, M. H. C. (2020, July 14-17). *A Bayesian Region of Measurement Equivalence (ROME) Approach for Establishing Measurement Invariance* [Poster Session]. Annual Meeting of the Psychometric Society (IMPS), College Park, MD, United States. [Schedule](https://www.psychometricsociety.org/sites/main/files/file-attachments/imps_2020_virtual_schedule_g1.pdf?1594692842)
</p>

<p>
- Tse, W. W. & Lai, M. H. C. (2020, June 25-26). *Measurement Invariance for Ordered Categorical Variables: The Necessity of Strict Invariance for Valid Group Comparisons* [Conference Session]. A Meeting of Methodologies (AMOM), Vancouver, BC, Canada. [Powerpoint slides](https://mfr.ca-1.osf.io/render?url=https://osf.io/qcfpg/?direct%26mode=render%26action=download%26mode=render)
</p>

<p>
- Lai, M. H. C. (2020, June 2-3). *Constructing bootstrap confidence intervals for standardized effect size in cluster-randomized trials* [Paper Session]. Modern Modeling Methods Conference (MMM), Storrs, CT, United States. (Conference canceled)
- Tse, W. W. & Lai, M. H. C. (2020, June 2-3). *Path to valid means comparisons: The necessity of strict measurement invariance for ordered categorical variables* [Poster Session]. Modern Modeling Methods Conference (MMM), Storrs, CT, United States. (Conference canceled)
- Zhang, Y. & Lai, M. H. C. (2020, June 2-3). *A Bayesian Region of Measurement Equivalence (ROME) Approach for Establishing Measurement Invariance* [Poster Session]. Modern Modeling Methods Conference (MMM), Storrs, CT, United States. (Conference canceled)
</p>