---
title: Research
author: ''
date: '2020-06-05'
slug: research
categories: []
tags: []
---

### Measurement

Measurement is the foundation of quantitative science, and it's especially important in psychological and social sciences. If a variable was not measured with good precision and validity, any research results based on it is like picking out patterns from random noise, or even highly misleading when systematic biases are present. 

Some current directions that we're working on include:

- Exploring new algorithms for adjusting parameter estimates for measurement noninvariance
- Correct steps for testing measurement invariance with categorical data
- Quantifying measurement noninvariance in a meaningful way
- Invariance conditions specific for composite (sum) scores
- Bias-correction methods for heterogeneous measurement errors
- Developing a Multidimensional Psychometric Framework on the Impact of Item Bias on Classification (Contract to begin with Army Research Institute)
<!-- - Summative index for systematic and random measurement errors -->

### Multilevel Modeling

Multilevel modeling, also called mixed-effect models, is an extremely powerful framework with very broad applications for quantitative science. It makes efficient use of data by adaptively pooling information across clusters (i.e., schools, states, companies, persons, or any continuous groups, including continuous ones). 

Some current directions that we're working on include:

- Bootstrap methods for calculating multilevel effect size statistics
- Bootstrap methods for handling unequal sampling probabilities
- Effect size indices in the presence of effect heterogeneity
- Defining reliability for clustered and longitudinal data
